<li><a href="#">introduction aux Résaux</a></li>
<li><a href="#">Electronique numerique I</a></li>
<li><a href="#">Système d'exploitation</a></li>
<li><a href="#">Programmation C</a></li>
<li><a href="#">Programmation Fonctionnel</a></li>
<li><a href="#">Programmation C++</a></li>
<li><a href="#">Anglais</a></li>
<li><a href="#">Analyse I</a></li>
<li><a href="#">Algebre II</a></li>
<li><a href="#">Architecture des ordinateurs</a></li>
<li><a href="#">introduction a l'algorithmique</a></li>
<li><a href="#">mecanique</a></li>